---
output:
  pdf_document: default
  html_document: default
---

<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->




# Literature Review {#lt-review}

This chapter presents the concepts of stochastic calculus, from the historic conception of how it first arose through the basic principles and applications in finance. More precisely, we address the classical Black-Scholes model and its limitations and the Heston model. This model is also well known, it introduces the concept of stochastic volatility which brings us closer to reality.

## Stochastic Calculus

Stochastic calculus arises from stochastic processes and allows the creation of a theory of integration where both the integrand and integrator terms are stochastic processes. Stochastic calculus, also known as, Itô calculus due to the name of it's creator, the Japanese mathematician Kiyosi Itô in the 1940s and 1950s is used for modelling financial options and in another wide variety of fields [@ubbo]. In this chapter we present the historical contexts in which the tools and models used arise, but our focus is introducing the concepts and notations that will be further used in our work.

[//]: is a generalization of the Riemann-Stieltjes integral 

### Brownian Motion

The Brownian motion is the name given to the irregular motion observed in the motion of pollen particles suspended in fluid resulting from particle collision with atoms or molecules. It is named after Robert Brown, the first to have observed the movement in 1828. He noted two characteristic in the pollen movement [@ubbo]:

* the path of a given particle is very irregular, having a tangent at no point

* the motion of two distinct particles appear to be independent

The first quantitative works in brownian motion come from an interest in stock price fluctuation by Bachelier in 1900. Albert Einstein also leaned over the subject and in 1905 derived the transition density for Brownian motion from molecular-kinetic theory of heat [@ubbo; @karatzas2012brownian].

In 1923, the Wiener process was coined in honor of Norbert Wiener mathematical proof of existence of the brownian motion and stating its properties as follows [@helgadottir2016option]:


*  $W_{0}=0$

* The change in $W$, given by $\Delta W = W_{t+1}-W_{t}$, is normally distributed with mean zero and standard deviation $\sqrt{\Delta t}$, meaning that $\Delta W = \epsilon\sqrt{\Delta t}$, where $\epsilon$ is $N(0,1)$.

* If the increment $\Delta t_1$ does not overlap with the time increment $\Delta t_2$, then $\Delta W_1$ and $\Delta W_2$ are independent.

* The process is continuous, meaning that there are no jumps in the process.

* The process is a Markov process. This means that the conditional expectation of $W_{t+1}$ given its entire history is equal to the conditional expectation of $W_{t+1}$ given today's information. This can be written as: $E[W_{t+1}|W_1, ..., W_t] = E[W_{t+1}|W_t]$.

* Consider the time interval $[0,t]$ with $n$ equally spaced intervals given by $t_i = \frac{it}{n}$. Then the paths of the Brownian motion have unbounded variation, this means that they are not differentiable and go towards infinity as $n$ increases. The quadratic variation is given by $\sum_{i=1}^{n}{(Z_{t_i}-Z_{t_{i-1}})^2} \rightarrow t$, meaning that when $n$ increases it stays constant at $t$.


### Correlated Brownian Motions {#corr}

Two independent brownian motions that are correlated can describe a new process $Z_t$. Let $W_1$ and $W_2$ be these two *independent* Brownian motions and let $-1 \leq \rho \leq 1$ be a given number. For $0 \leq t \leq T$ define the new process $Z_t$ as [@ubbo]:

\begin{align}
\label{eq:corr_brow}
Z_t = \rho W_{1,t} + \sqrt{1-\rho^2}W_{2,t}
\end{align}

\noindent
This equation is a linear combination of independent normals at each timestep $t$, so $Z_t$ is normally distributed. It is proven that $Z$ is a Brownian motion and that $Z$ and $W_{1,t}$ are correlated [@ubbo, pp. 514].




### Arithmetic Brownian Motion

The arithmetic brownian motion is defined in literature as being a random process (S) defined as follows [@ubbo]:

\begin{align}
dS_t = \mu dt + \sigma dB_t
\end{align}

\begin{center}or in integral form:\end{center}

\begin{align}
\int_{t=0}^{T} dS_t = \int_{t=0}^{T}{\mu dt} + \int_{t=0}^{T}{\sigma dB_t}
\end{align}


\noindent
Where, $\mu$ and $\sigma$ are known and constant with $\sigma > 0$. In this process, both the drift $\mu$ and the diffusion $\sigma$ coefficient are constant. The expected value of this process is the sum of the initial value and the drift times the elapsed period ($S_0 + \mu T$). The variance is described by $\sigma^2 T$


### Geometric Brownian Motion

A stochastic process $S_t$ is a geometric brownian motion if its solution is described by the solution of the following stochastic differential equation [@tong2012option; @tsay2005analysis].

\begin{align}
dS_t = \mu S_t dt + \sigma S_t dW_t
\end{align}

\noindent
for given constants $\mu \in {\rm I\!R}$ and $\sigma > 0$. Also, the assumed initial value is positive, $S_0 >0$.

This process is used quite often in finance to model the dynamics of some assets becaus of its properties. It has independent multiplicative increments and its solution is presented below[@iacus2009simulation]:


\begin{align}
S_t = S_0 \times exp{\left(\mu - \frac{\sigma^2}{2} \right) t + \sigma W_t}, \;\; t > 0
\end{align}



### Itô's Calculus

Let $X_{t}$ be a real-valued stochastic process that satisfies [@tong2012option; @evans2012introduction; @steele2012stochastic]:

\begin{align}
S_t = S_0 + \int_{0}^{t} \mu_t dt + \int_{0}^{t} \sigma_t dW_t
\end{align}

\noindent
for some $\mu_t$, $\sigma_t$ and $t \in [0,T]$. This equation is often rewritten in its differential stochastic form:

\begin{align}
dS_t = \mu_t dt + \sigma_t dW_t 
\end{align}

\noindent
for $0 \leq t \leq T$.

\begin{theorem}[Itô's Lemma]
Assume that $S_t$ has a stochastic differential given by:

\begin{align}
dS_t = \mu_t dt + \sigma_t dW_t 
\end{align}

\noindent
for $\mu_t$, $\sigma_t$ and $t \in [0,T]$. Assume $u: \mathbb{R} \times [0, T] \rightarrow \mathbb{R}$ is continuous and that $\frac{\partial u}{\partial t}$, $\frac{\partial u}{\partial x}$, $\frac{\partial^2 u}{\partial x^2}$ exist and are continuous.

$$Y_t := u(S_t, t)$$
\noindent
Then Y has the following stochastic differential:

\begin{align} 
\label{eq:ito}
\begin{split}
    dY_t &= \frac{\partial u}{\partial t}dt + \frac{\partial u}{\partial x} dS_t + \frac{1}{2}\frac{\partial^2 u}{\partial x^2}\sigma_t^2 dt  \\[10pt] 
    &= \left( \frac{\partial u}{\partial t} + \mu_t \frac{\partial u}{\partial x} + \frac{1}{2}\frac{\partial^2 u}{\partial x^2}\sigma_t^2 \right) dt + \sigma_t \frac{\partial u}{\partial x} dW_t
\end{split}
\end{align}

\noindent 
where the argument of $u$, $\frac{\partial u}{\partial x}$ and $\frac{\partial^2 u}{\partial x^2}$ above is $\left( S_t, t \right)$ .
\end{theorem}



#### Derivação

\begin{align}
dS_t = \mu S_t dt + \sqrt{V_t} S_t dB_t
\end{align}

If $S$ were deterministic, $dS_t/S_t$ would be the derivative of $ln(S_t)$ with respect to $S$. This suggests to find an expression for the stochastic differential of $ln(S_t)$, a function of the single random variable $S_t$.

\begin{scriptsize}
\begin{align}
df(t,S) &= \cancelto{0}{\frac{\partial f}{\partial t}dt}  + \frac{\partial f}{\partial S} dS + \cancelto{0}{\frac{1}{2} \frac{\partial^2 f}{\partial t^2} (dt)^2} + \frac{1}{2} \frac{\partial^2 f}{\partial S^2} (dS)^2  + \cancelto{0}{\frac{\partial^2 f}{\partial t \partial S} dt dS} \\
f(t,S) &= ln(S) \\
dln(S) &= \frac{dln(S)}{dS} dS + \frac{1}{2} \frac{d^2ln(S)}{dS^2}(dS)^2 \\
dln(S) &= \frac{1}{S} (\mu S dt + \sqrt{V} S dB) + \frac{1}{2}\frac{-1}{S^2}\sqrt{V}^2 S^2 dt \\
dln(S) &= \left( \mu -  \frac{1}{2} V \right) dt + \sqrt{V} dB \\
\int_{u}^{T}{dln(S)} &= \int_{u}^{T}{\left( \mu - \frac{1}{2} V_t \right) dt} + \int_{u}^{T}{\sqrt{V_t}dB_t} \\
ln(S_t) - ln(S_u) &= \int_{u}^{T}{\left( \mu - \frac{1}{2} V_t \right) dt} + \int_{u}^{T}{\sqrt{V_t}dB_t} \\
ln \left( \frac{S_t}{S_u} \right) &= \mu (t-u) - \frac{1}{2}\int_{u}^{T}{V_t dt} + \int_{u}^{T}{\sqrt{V_t} dB_t} \\
ln \left( \frac{S_t}{S_u} \right) &= \mu (t-u) - \frac{1}{2}\int_{u}^{T}{V_t dt} + \int_{u}^{T}{\sqrt{V_t} \left(\rho dB_{1,s} + \sqrt{1-\rho^2} dB_{1,s} \right)} \\
S_t &= S_u \times \exp \left( \mu (t-u) - \frac{1}{2} \int_{u}^{T}{V_t dt} + \rho \int_{u}^{T}{\sqrt{V_t}dB_{1,t}}+ \sqrt{1 - \rho^2} \int_{u}^{T}{\sqrt{V_t}dB_{2,t}} \right)
\end{align}
\end{scriptsize}






Equation \@ref(eq:ito) is the stochastic equivalent to the chain rule, also known as Itô's formula or Itô's chain rule. The proof to this theorem is based on the Taylor expansion of the function $f(S_t, t)$ [@tong2012option; @evans2012introduction]. For practical uses you should write out a second-order Taylor expansion for the function to be analyzed and apply the     \@ref(tab:box-calc)  multiplication table [@ubbo].

```{r box-calc, echo=FALSE, message=FALSE, results='asis'}
mat <- matrix(c(0, 0, 0, "$dt$"), nrow = 2, ncol = 2)
rownames(mat) <- c("$dt$", "$dW_t$")
colnames(mat) <- c("$dt$", "$dW_t$")
#align(mat) <- c("|c","c","c|")
#print(mat, sanitize.text.function = function(x) {x})
knitr::kable(mat, caption = 'Box calculus', align = c('l','r', 'r'),
             longtable = TRUE, booktabs = TRUE, escape = FALSE)
```










## Black-Scholes Model

The Black-Scholes (B-S) model arises from the need to price european options in the derivative markets. Derivatives are financial instruments traded in the market, stock exchange or over-the-counter (OTC) market, whose values depend on the values of an underlying asset. [@yang2013valuing; @salomao2011precificaccao; @black1973pricing]

* A call option is a derivative that gives its bearer the right, but not the obligation, to purchase a specific asset by a fixed price before or on a given date. 

* A put option is a derivative that gives its bearer the right, but not the obligation, to sell a specific asset by a fixed price before or on a given date.

The trading price of the option is called the option *premium* and the asset from which the option derives is called the *underlying asset*. This asset may be the interest rate, exchange rates, stock exchanges rates, commodities or stocks. The fixed price in contract in which the underlying asset might to be bought or sold is the *strick price*. The option expiration date is called the *maturity*. [@salomao2011precificaccao; @black1973pricing]

There are two major different option types: the European and the American. The difference between these two is that the bearer of the first may exercise it only at the end of its life, at its maturity while the latter can be exercised at any given time until its maturity. [@black1973pricing; @merton1973theory]


### The model

The Black-Scholes model that provides analytical solution to the price of a European call at time $t$ can be described as follows[@yang2013valuing; @black1973pricing; @helgadottir2016option]:

\begin{align}
C(S_{t},t)&=N(d_{1})S_{t}-N(d_{2})Ke^{-r(T-t)}\\[10pt]
d_{1}&={\frac {1}{\sigma {\sqrt {T-t}}}}\left[\ln \left({\frac {S_{t}}{K}}\right)+\left(r+{\frac {\sigma ^{2}}{2}}\right)(T-t)\right]\\[10pt]
d_{2}&=d_{1}-\sigma {\sqrt {T-t}}
\end{align}




\noindent
Where:

* $S_{t}$ is the spot price of the underlying asset at time $t$
* $r$ is the risk free rate (generally an annual rate)\footnote{Assumed to be constant. \label{teste}}
* $\sigma$ is the volatility of returns of the underlying asset \footnote{See footnote 1.}
* $N(\cdot )$ is the cumulative distribution function of the standard Gaussian distribution
* $K$ is the strike price
* $T-t$ is the time to maturity 


\noindent
Also, the stock price path is a Geometric Brownian Motion and is under the risk-neutral measure with the following dynamics [@helgadottir2016option; @nmof]: 

\begin{align}
dS_{t} = (r-q)S_td_t+\sigma S_t dW_t
\end{align}

\noindent
Where $dW_t$ is a Wiener process [@black1973pricing; @nmof], $r$ is the risk free rate and $q$ is the dividend yield\footnote{$r$ and $q$ are assumed to be constant.} and $t$ denotes the current point in time. 


Although the Black-Scholes is very popular and the *de facto* standard in the market there are implications to the B-S model assumptions that affect the results and that are unrealistic. The main assumption that does not hold up is the deterministic (constant) volatility, that can more accurately be described as a stochastic process since we observe that small moves usually are followed by small moves and large moves by large moves.   [@yang2013valuing; @helgadottir2016option]

Other assumptions that are critical to the B-S model and are not always observed in practice refer to the asset's continuity through time (no jumps), being allowed to perform continuous hedge without transactions costs and normal (Gaussian) returns.

Most models focus on the volatility problem because transaction costs often translate to rises in volatility and fat-tails (abnormal) returns can be simulated by stochastic volatility and market or volatility jumps.




<!-- Out of all the parameters that the call price depends on in the Black Scholes -->
<!-- model, the volatility is the only one that is unobservable, but we can let the -->
<!-- market of liquid derivatives decide which volatility has to be plugged in the -->
<!-- model. The calibrated σ* is the one that fits best the model prices to the observed -->
<!-- market prices, by minimizing the sum of square errors: -->
<!-- σ ∗ = arg q 	min -->
<!-- 2,o -->
<!-- C mn S " , K 2 , σ, T o − C p S", K 2 , T o -->
<!-- . -->
<!-- Knowing S, K, T, r, q and the quoted option call value it is possible to extract the -->
<!-- implied volatility. -->




<!-- [@tong2012option] -->
<!-- Using Black-Scholes option pricing model, the price of a call option is the function of -->
<!-- the spot (current) price S(0), interest rate r, the strike K, the constant volatility σ -->
<!-- and the maturity T . Except for the volatility σ, all the other variables are observable. -->
<!-- Since the quoted option price C obs is observable, using the Black-Scholes formula we -->
<!-- can therefore calculate or imply the volatility that is consistent with the quoted his- -->
<!-- torical option prices and observed variables. We can therefore define implied volatility -->
<!-- σimpl by -->
<!-- C BS (0; r, K, T, σimpl , S(0)) = C obs -->
<!-- where C BS is the option price calculated by the Black-Scholes formula (equation -->
<!-- (3.3.9)). Implied volatility surfaces are graphs plotting σimpl for each call option’s -->
<!-- strike K and expiration T . Theoretically, options whose underlying is governed by -->
<!-- the geometric Brownian motion should have a flat implied volatility surface, since -->
<!-- volatility is a constant. -->


<!-- [@yang2013valuing] -->
<!-- Volatility is a measure for variation of price of a stock over time. Stochastic volatility is described as -->
<!-- processes in which the return variation dynamics include an unobservable shock that cannot be predicted -->
<!-- using current available information. Stochastic volatility models, which let the volatility follow Brownian -->
<!-- motion, make the option price much better adapted to the realities of the market. -->


## Stochastic Volatility models

Introducing stochastic volatility to models brings complexity, but enables modeling some features observed in reality that are crucial like the randomic market volatility effects, skewness (market returns are more realistically modeled) and volatility smile. This kind of model is applied highly succesfully in foreign exchange and credit markets.



 
### Cox-Ingersoll-Ross model
 
 The Cox-Ingersoll-Ross (CIR) model is a well-known short-rate model that describes the interest rate movements driven by one source of market risk. The dynamics are described as follows[@cox1985theory; @heston1993closed]:
 
\begin{align}
\label{eq:cir}
dr_t &= k(\theta - r_t)dt + \sigma \sqrt{r_t} dB_t
\end{align} 

\noindent
Where, $r_t$ is the short rate interest described by parameters $k$ - the speed of mean reversion, $\theta$ - the long-run mean variance and $\sigma$ - the volatility of the variance process.

This model has been widely used to describe the dynamics of the short rate interest because it has some fundamental features like intuitive parametrization, nonnegativity and pricing formulas. Besides, it takes account of anticipations, risk aversion, investment alternatives and preferences about consumption timing and allows for detailed predictions about how changes in a wide range of underlying variables affect the term structure[@cox1985theory].
Furthermore, this equation constitutes one of the two Heston model equations with the volatility taking the short rate interest place.


### Heston Model

Heston model solves the deterministic volatility problems introducing the following equations, which represents the dynamics of the stock price and the variance processes under the risk-neutral measure [@gilli_numerical_2011; @heston1993closed]:


\begin{align}
\label{eq:heston}
\begin{split}
dS_t &= \mu S_t dt + \sqrt{V_t} S_t dW^*_t \\
dV_t &= k(\theta - V_t)dt + \sigma \sqrt{V_t} dB_t
\end{split}
\end{align}



The second equation, as previously described, is the CIR model equation. The first equation states the asset price process. $\mu$ is the asset's rate of return,  $dW_{t,1}$ and $dW_{t,2}$ are two correlated wiener processes with correlation coefficient of $\rho$. Because, of the model specifications and what we presentend in section \@ref(corr), we can rewrite the first equation as in Broadie and Kaya [@broadie2006exact]:

\begin{align}
\label{eq:heston2}
\begin{split}
dS_t &= \mu S_t dt + \rho \sqrt{V_t} dB_t + \sqrt{1 - \rho^2} \sqrt{V_t} S_t dW_t \\
dV_t &= k(\theta - V_t)dt + \sigma \sqrt{V_t} dB_t
\end{split}
\end{align}






### Other models




















<!-- * Model -->


<!-- It's easy to create a list.  It can be unordered like -->

<!-- * Item 1 -->
<!-- * Item 2 -->

<!-- or it can be ordered like -->

<!-- 1. Item 1 -->
<!-- 4. Item 2 -->

<!-- Notice that I intentionally mislabeled Item 2 as number 4.  _Markdown_ automatically figures this out!  You can put any numbers in the list and it will create the list.  Check it out below. -->

<!-- To create a sublist, just indent the values a bit (at least four spaces or a tab).  (Here's one case where indentation is key!) -->

<!-- 1. Item 1 -->
<!-- 1. Item 2 -->
<!-- 1. Item 3 -->
<!--     - Item 3a -->
<!--     - Item 3b -->

<!-- ## Line breaks -->

<!-- Make sure to add white space between lines if you'd like to start a new paragraph.  Look at what happens below in the outputted document if you don't: -->

<!-- Here is the first sentence.  Here is another sentence.  Here is the last sentence to end the paragraph. -->
<!-- This should be a new paragraph. -->

<!-- *Now for the correct way:* -->

<!-- Here is the first sentence.  Here is another sentence.  Here is the last sentence to end the paragraph. -->

<!-- This should be a new paragraph. -->

<!-- ## R chunks -->

<!-- When you click the **Knit** button above a document will be generated that includes both content as well as the output of any embedded **R** code chunks within the document. You can embed an **R** code chunk like this (`cars` is a built-in **R** dataset): -->

<!-- ```{r cars} -->
<!-- summary(cars) -->
<!-- ``` -->

<!-- ## Inline code -->

<!-- If you'd like to put the results of your analysis directly into your discussion, add inline code like this: -->

<!-- > The `cos` of $2 \pi$ is `r cos(2*pi)`. -->

<!-- Another example would be the direct calculation of the standard deviation: -->

<!-- > The standard deviation of `speed` in `cars` is `r sd(cars$speed)`. -->

<!-- One last neat feature is the use of the `ifelse` conditional statement which can be used to output text depending on the result of an **R** calculation: -->

<!-- > `r ifelse(sd(cars$speed) < 6, "The standard deviation is less than 6.", "The standard deviation is equal to or greater than 6.")` -->

<!-- Note the use of `>` here, which signifies a quotation environment that will be indented. -->

<!-- As you see with `$2 \pi$` above, mathematics can be added by surrounding the mathematical text with dollar signs.  More examples of this are in [Mathematics and Science] if you uncomment the code in [Math]. -->

<!-- ## Including plots -->

<!-- You can also embed plots.  For example, here is a way to use the base **R** graphics package to produce a plot using the built-in `pressure` dataset: -->

<!-- ```{r pressure, echo=FALSE, cache=TRUE} -->
<!-- plot(pressure) -->
<!-- ``` -->

<!-- Note that the `echo=FALSE` parameter was added to the code chunk to prevent printing of the **R** code that generated the plot.  There are plenty of other ways to add chunk options.  More information is available at <http://yihui.name/knitr/options/>. -->

<!-- Another useful chunk option is the setting of `cache=TRUE` as you see here.  If document rendering becomes time consuming due to long computations or plots that are expensive to generate you can use knitr caching to improve performance.  Later in this file, you'll see a way to reference plots created in **R** or external figures. -->

<!-- ## Loading and exploring data -->

<!-- Included in this template is a file called `flights.csv`.  This file includes a subset of the larger dataset of information about all flights that departed from Seattle and Portland in 2014.  More information about this dataset and its **R** package is available at <http://github.com/ismayc/pnwflights14>.  This subset includes only Portland flights and only rows that were complete with no missing values.  Merges were also done with the `airports` and `airlines` data sets in the `pnwflights14` package to get more descriptive airport and airline names. -->

<!-- We can load in this data set using the following command: -->

<!-- ```{r load_data} -->
<!-- flights <- read.csv("data/flights.csv") -->
<!-- ``` -->

<!-- The data is now stored in the data frame called `flights` in **R**.  To get a better feel for the variables included in this dataset we can use a variety of functions.  Here we can see the dimensions (rows by columns) and also the names of the columns. -->

<!-- ```{r str} -->
<!-- dim(flights) -->
<!-- names(flights) -->
<!-- ``` -->

<!-- Another good idea is to take a look at the dataset in table form.  With this dataset having more than 50,000 rows, we won't explicitly show the results of the command here.  I recommend you enter the command into the Console **_after_** you have run the **R** chunks above to load the data into **R**. -->

<!-- ```{r view_flights, eval=FALSE} -->
<!-- View(flights) -->
<!-- ``` -->

<!-- While not required, it is highly recommended you use the `dplyr` package to manipulate and summarize your data set as needed.  It uses a syntax that is easy to understand using chaining operations.  Below I've created a few examples of using `dplyr` to get information about the Portland flights in 2014.  You will also see the use of the `ggplot2` package, which produces beautiful, high-quality academic visuals. -->

<!-- We begin by checking to ensure that needed packages are installed and then we load them into our current working environment: -->

<!-- ```{r load_pkgs, message=FALSE} -->
<!-- # List of packages required for this analysis -->
<!-- pkg <- c("dplyr", "ggplot2", "knitr", "bookdown", "devtools") -->
<!-- # Check if packages are not installed and assign the -->
<!-- # names of the packages not installed to the variable new.pkg -->
<!-- new.pkg <- pkg[!(pkg %in% installed.packages())] -->
<!-- # If there are any packages in the list that aren't installed, -->
<!-- # install them -->
<!-- if (length(new.pkg)) -->
<!--   install.packages(new.pkg, repos = "http://cran.rstudio.com") -->
<!-- # Load packages (thesisdown will load all of the packages as well) -->
<!-- library(thesisdown) -->
<!-- ``` -->

<!-- \clearpage -->

<!-- The example we show here does the following: -->

<!-- - Selects only the `carrier_name` and `arr_delay` from the `flights` dataset and then assigns this subset to a new variable called `flights2`. -->

<!-- - Using `flights2`, we determine the largest arrival delay for each of the carriers. -->

<!-- ```{r max_delays} -->
<!-- flights2 <- flights %>% -->
<!--   select(carrier_name, arr_delay) -->
<!-- max_delays <- flights2 %>% -->
<!--   group_by(carrier_name) %>% -->
<!--   summarize(max_arr_delay = max(arr_delay, na.rm = TRUE)) -->
<!-- ``` -->

<!-- A useful function in the `knitr` package for making nice tables in _R Markdown_ is called `kable`.  It is much easier to use than manually entering values into a table by copying and pasting values into Excel or LaTeX.  This again goes to show how nice reproducible documents can be! (Note the use of `results="asis"`, which will produce the table instead of the code to create the table.)  The `caption.short` argument is used to include a shorter title to appear in the List of Tables. -->

<!-- ```{r maxdelays, results="asis"} -->
<!-- kable(max_delays, -->
<!--       col.names = c("Airline", "Max Arrival Delay"), -->
<!--       caption = "Maximum Delays by Airline", -->
<!--       caption.short = "Max Delays by Airline", -->
<!--       longtable = TRUE, -->
<!--       booktabs = TRUE) -->
<!-- ``` -->

<!-- The last two options make the table a little easier-to-read. -->

<!-- We can further look into the properties of the largest value here for American Airlines Inc.  To do so, we can isolate the row corresponding to the arrival delay of 1539 minutes for American in our original `flights` dataset. -->


<!-- ```{r max_props} -->
<!-- flights %>% filter(arr_delay == 1539, -->
<!--                   carrier_name == "American Airlines Inc.") %>% -->
<!--   select(-c(month, day, carrier, dest_name, hour, -->
<!--             minute, carrier_name, arr_delay)) -->
<!-- ``` -->

<!-- We see that the flight occurred on March 3rd and departed a little after 2 PM on its way to Dallas/Fort Worth.  Lastly, we show how we can visualize the arrival delay of all departing flights from Portland on March 3rd against time of departure. -->

<!-- ```{r march3plot, fig.height=3, fig.width=6} -->
<!-- flights %>% filter(month == 3, day == 3) %>% -->
<!--   ggplot(aes(x = dep_time, y = arr_delay)) + geom_point() -->
<!-- ``` -->

<!-- ## Additional resources -->

<!-- - _Markdown_ Cheatsheet - <https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet> -->

<!-- - _R Markdown_ Reference Guide - <https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf> -->

<!-- - Introduction to `dplyr` - <https://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html> -->

<!-- - `ggplot2` Documentation - <http://docs.ggplot2.org/current/> -->
