# Models

<!-- Required to number equations in HTML files -->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>


## Teste

```{r call, eval=FALSE}
Call <- function(S,X,tau,r,q,sigma){
  
  # S = spot
  # X = strike
  # tau = time to maturity
  # r = riskfree rate
  # q = dividend yield
  # sigma = standard deviation
  
  d1 = (log(S/X) + (r - q + sigma^2/2) * tau) / (sqrt(sigma^2 * tau))
  d2 = d1 - sqrt(sigma^2 * tau)
  c0 = S * exp(-q * tau) * pnorm(d1,0,1) -
       X * exp(-r * tau) * pnorm(d2,0,1)

  return(c0)
}
```

\clearpage

```{r euler_call, eval=FALSE}

euler_call <- function(X0, mu, sigma, Dt = 0.1, t=0, T=1, 
                       N = 1000, K = 0, plt=FALSE){
  X0 = rep(X0,N)                     # initial values
  lines = floor((T-t)/Dt + 1)       
  w = matrix(nrow=lines, ncol = N)  # matrix with N columns
  n = seq(from=(Dt+t), to=T, by=Dt)  # steps
  w[1,] = X0                         
  l2 = lines-1                      
  bw = sqrt(Dt)*rnorm(N*l2,0,1)      # random gaussian numbers
  bw = matrix(bw, nrow = l2, 
              ncol = N)              
  for (i in seq_along(n)){
      w[i+1,] = w[i,] + mu *w[i,] *Dt + sigma * w[i,] * bw[i,]
  }
  Result = w[lines,] - K
  Result[Result <= 0] = 0
  call = exp(-mu*T)*mean(Result)
  if (plt == TRUE){
      matplot(w, ylim = c(min(w),max(w)), axes=F, 
              lty=1, pch = 20 , type="l")
      grid()
      if (N <= 10 && lines <= 6){
          for (i in seq_along(w[1,])){
              points(w[,i], col='red', pch=20)
          }
      }
      if (K != 0){
          abline(h=K, col='red', lwd = 3)
      }
      box()
      axis(side = 1, at= seq(1,lines,lines-1), 
           labels=c('0', as.character(lines-1)))
      axis(side = 2, las = 1)
  }
  res = list('realizations' = as.data.frame(w), 
               'mean' = mean(w[lines,]),
               'solution' = w[lines,], 'eurocall' = call)
  return(invisible(res))
}

```